POSTGRES:
  USER: !ENV ${PG_USER}
  PASSWORD: !ENV ${PG_PASSWORD}
  HOST: ec2-52-208-221-89.eu-west-1.compute.amazonaws.com
  PORT: 5432
  DATABASE: d77pd2039kr87n
  file_name: src/database/database_structure.sql
TG:
  TOKEN: !ENV ${TG_TOKEN}
VK:
  TOKEN: !ENV ${VK_TOKEN}
  METHOD: board.getTopics
  PARAMS: !ENV ${VK_PARAMS}
  VERSION: 5.131