DROP TABLE IF EXISTS Topics;
DROP TABLE IF EXISTS Subscribers;

CREATE TABLE Topics(
Id SERIAL PRIMARY KEY,
Description TEXT NOT NULL,
Created TIMESTAMP NOT NULL
 );

CREATE TABLE Subscribers(
Id SERIAL PRIMARY KEY
 );